// electron/license.js
// Mizan Suite offline license verification (runs INSIDE the app, in the Electron main
// process). Ships with only the PUBLIC key embedded - it can verify licenses but
// can never create new ones. Key generation lives in license-tools/ on your PC.

const nacl = require('tweetnacl');
const util = require('tweetnacl-util');
const fs = require('fs');
const path = require('path');
const { machineIdSync } = require('node-machine-id');

// Public half of the keypair held in license-tools/. Generated by
// `node generate-license.js --export-public`. Keep in sync with that file.
const PUBLIC_KEY_B64 = 'K4owXn6NECgh6ZlKFPtKCHzdT8qT2R5BjlISkRZ2KMM=';
const PUBLIC_KEY = util.decodeBase64(PUBLIC_KEY_B64);

// Public half of the SEPARATE trial keypair (license-tools/trial-public.key,
// created with `node generate-trial-keys.js`). Trial keys are signed with the
// trial private key on the trial server, so that server never holds the master
// private key. The app accepts signatures from either key.
const TRIAL_PUBLIC_KEY_B64 = '/fYb4rjDGkfgvKqCm3m62aMKwHrt5gHvhoep6nlkijE=';
const TRIAL_PUBLIC_KEY = util.decodeBase64(TRIAL_PUBLIC_KEY_B64);

const KEY_PREFIX = 'MZN-'; // must match license-tools/generate-license.js

// When the hardware fingerprint changes (Windows update, new drive, etc.) we
// still allow the app to run for this long since the last good use, so a paying
// client is never cold-locked by a driver update. Contact the developer for a
// fresh key once this window passes.
const GRACE_MS = 3 * 24 * 60 * 60 * 1000; // 3 days

// Parses a license key string into { payload, payloadBytes } or returns null.
function parseLicenseKey(keyString) {
  if (!keyString || typeof keyString !== 'string') return null;
  const body = keyString.trim().startsWith(KEY_PREFIX) ? keyString.trim().slice(KEY_PREFIX.length) : keyString.trim();
  const dot = body.indexOf('.');
  if (dot <= 0) return null;
  const payloadB64 = body.slice(0, dot);
  const sigB64 = body.slice(dot + 1);
  if (!payloadB64 || !sigB64) return null;
  try {
    const payloadBytes = util.decodeBase64(payloadB64);
    const sigBytes = util.decodeBase64(sigB64);
    return { payloadBytes, sigBytes };
  } catch (e) {
    return null;
  }
}

// Verifies a license key. Returns:
//   { ok: true, payload }
//   { ok: false, reason, payload? }
// A key is accepted if its signature verifies against the master public key OR
// the trial public key (trial keys are signed on the trial server with a key
// that is never allowed to create paid licenses).
// `publicKeyOverride` is used only by tests to verify against a throwaway keypair.
function verifyLicense(keyString, nowMs = Date.now(), publicKeyOverride) {
  const parsed = parseLicenseKey(keyString);
  if (!parsed) return { ok: false, reason: 'invalid_key' };

  const pubs = publicKeyOverride ? [publicKeyOverride] : [PUBLIC_KEY, TRIAL_PUBLIC_KEY];
  let valid = false;
  for (const pub of pubs) {
    try {
      if (nacl.sign.detached.verify(parsed.payloadBytes, parsed.sigBytes, pub)) {
        valid = true;
        break;
      }
    } catch (e) {
      // nacl throws (rather than returning false) on a malformed signature size.
    }
  }
  if (!valid) return { ok: false, reason: 'invalid_signature' };

  let payload;
  try {
    payload = JSON.parse(util.encodeUTF8(parsed.payloadBytes));
  } catch (e) {
    return { ok: false, reason: 'invalid_key' };
  }

  // Expiry check.
  if (payload.expires) {
    const exp = new Date(payload.expires).getTime();
    if (!isNaN(exp) && nowMs > exp) {
      return { ok: false, reason: 'expired', payload };
    }
  }

  // Machine check: only enforced if the license carries a machineId.
  if (payload.machineId) {
    const current = getMachineId();
    if (current && payload.machineId !== current) {
      return { ok: false, reason: 'wrong_machine', payload };
    }
  }

  return { ok: true, payload };
}

// Stable hardware fingerprint. Falls back to null if unavailable (then machine
// locking is skipped, which is the right thing for a broken/odd environment).
function getMachineId() {
  try {
    return machineIdSync();
  } catch (e) {
    return null;
  }
}

// ---------- stored license (persists the raw key in userData) ----------

function licenseFilePath(userDataDir) {
  return path.join(userDataDir, 'license.json');
}

function stateFilePath(userDataDir) {
  return path.join(userDataDir, 'license-state.json');
}

function loadStoredLicense(userDataDir) {
  try {
    const raw = fs.readFileSync(licenseFilePath(userDataDir), 'utf8').trim();
    const obj = JSON.parse(raw);
    return typeof obj.key === 'string' ? obj.key : null;
  } catch (e) {
    return null;
  }
}

function saveLicense(userDataDir, keyString) {
  const file = licenseFilePath(userDataDir);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify({ key: keyString, savedAt: new Date().toISOString() }));
}

// Remembers the most recent valid-use timestamp, so a hardware change can be
// given a short grace period. Only updated on a fully valid, machine-matching
// check - otherwise the grace window would keep extending forever.
function touchLastValid(userDataDir, nowMs = Date.now()) {
  try {
    const file = stateFilePath(userDataDir);
    let lastSeen = nowMs;
    try {
      const prev = JSON.parse(fs.readFileSync(file, 'utf8'));
      if (prev && typeof prev.lastSeen === 'number') lastSeen = Math.max(prev.lastSeen, nowMs);
    } catch (e) {}
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, JSON.stringify({ lastSeen }));
  } catch (e) {}
}

function lastValidTime(userDataDir) {
  try {
    const obj = JSON.parse(fs.readFileSync(stateFilePath(userDataDir), 'utf8'));
    return typeof obj.lastSeen === 'number' ? obj.lastSeen : null;
  } catch (e) {
    return null;
  }
}

// Full app-level check used at every launch:
//   1. no stored license                      -> needs activation
//   2. signature/format bad                   -> invalid
//   3. expired                                -> expired (needs renewal key)
//   4. machine mismatch, within grace         -> ok (warned), grace continues
//   5. machine mismatch, grace over           -> wrong_machine
//   6. clock moved backwards suspiciously     -> clock_rollback
// Returns { status, reason?, payload?, client? }.
function checkLicenseStatus(userDataDir, nowMs = Date.now(), publicKeyOverride) {
  const key = loadStoredLicense(userDataDir);
  if (!key) return { status: 'unlicensed', reason: 'no_key' };

  const result = verifyLicense(key, nowMs, publicKeyOverride);
  if (!result.ok) {
    if (result.reason === 'wrong_machine') {
      // Grace period on hardware change.
      const last = lastValidTime(userDataDir);
      if (last !== null && nowMs - last <= GRACE_MS && nowMs >= last) {
        return { status: 'ok', reason: 'machine_grace', client: result.payload ? result.payload.client : null, payload: result.payload };
      }
      return { status: 'wrong_machine', reason: 'wrong_machine', client: result.payload ? result.payload.client : null };
    }
    if (result.reason === 'expired') return { status: 'expired', reason: 'expired', client: result.payload ? result.payload.client : null };
    return { status: 'invalid', reason: result.reason };
  }

  // Clock rollback guard: if the wall clock jumps far backwards vs our last good
  // use, someone is probably winding the clock back to dodge expiry.
  const last = lastValidTime(userDataDir);
  if (last !== null && nowMs < last - GRACE_MS) {
    return { status: 'clock_rollback', reason: 'clock_rollback', client: result.payload.client };
  }

  touchLastValid(userDataDir, nowMs);
  return { status: 'ok', reason: 'valid', client: result.payload.client, payload: result.payload };
}

module.exports = {
  PUBLIC_KEY_B64,
  TRIAL_PUBLIC_KEY_B64,
  KEY_PREFIX,
  verifyLicense,
  getMachineId,
  loadStoredLicense,
  saveLicense,
  touchLastValid,
  lastValidTime,
  checkLicenseStatus,
  parseLicenseKey
};
